export enum Status {
  TRANSACTION_SUCCESSFUL = 1,
  TRANSACTION_FAILED = 2,
}

export enum Type {
  TRANSACTION_TYPE_UNSPECIFIED = 0,
  TRANSACTION_TYPE_XHR = 1,
  TRANSACTION_TYPE_FETCH = 2,
  TRANSACTION_TYPE_WEBSOCKET = 3,
  TRANSACTION_TYPE_HTTP = 4,
  TRANSACTION_TYPE_GRPC = 5,
  TRANSACTION_TYPE_DB = 6,
  TRANSACTION_TYPE_INTERNAL = 7,
  TRANSACTION_TYPE_ROUTER = 8,
}
